version: '3.8'

services:
  ## mysql:  # The hostname for the mysql service will be the service name itself (mysql)
  localhost:  # The hostname for the mysql service.
    image: mariadb:lts-alpine
    environment:
      #
      # `environment` passes the variables into the container's environment (so
      # your PHP app can access them).
      #
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      #
      ## MYSQL_USER: ${DB_USER}      # Only if you want a non-root user
      ## MYSQL_PASSWORD: ${DB_PASS}  # Only if you want a non-root user
      #
      MYSQL_DATABASE: ${DB_NAME}
      #
      MYSQL_VOLUME: ./mysql_data  # Used only in docker-compose.yml.

    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
      #
      # Mount the init-db.sql file into the container at a known path:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  php:
    build:
      context: .
      args:
        ENVIRONMENT: development
    ports:
      - "8080:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      #
      # Overrides those files in Dockerfile during development for live reloading.
      # Might be useful to have for 
      # * Active development
      # * Debugging
      #
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./.htaccess.production:/var/www/html/.htaccess
      - ./config/apache-config.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      ## mysql:
      localhost:
        condition: service_healthy
