version: '3.8'

services:
  mysql:  # The hostname for the mysql service will be the service name itself (mysql)
    image: mariadb:lts-alpine
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}  # Required for MySQL 8.0
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}      # Only if you want a non-root user
      MYSQL_PASSWORD: ${DB_PASS}  # Only if you want a non-root user
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
      #
      # Mount the init-db.sql file into the container at a known path:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  php:
    build:
      context: .
      args:
        ENVIRONMENT: production
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      mysql:
        condition: service_healthy
