#!/usr/bin/env sh

# -------------------------------------------------
# Configuration:
# -------------------------------------------------
SCRIPT_NAME=$(basename "$0")

HTACCESS_FILE=".htaccess.development"

# -------------------------------------------------
#  Load variables from .env.development
# -------------------------------------------------
set -a                     # export every assignment

# source the file – POSIX sh uses '.' (dot) for this
. ./env/.env.development

set +a                     # stop automatic export

# -------------------------------------------------
# Replace SetEnv lines in-place using sed
# -------------------------------------------------

sed -i \
  -e "/^SetEnv DB_HOST /  s|.*|SetEnv DB_HOST \"${DB_HOST}\"|" \
  -e "/^SetEnv DB_USER /  s|.*|SetEnv DB_USER \"${DB_USER}\"|" \
  -e "/^SetEnv DB_PASS /  s|.*|SetEnv DB_PASS \"${DB_PASS}\"|" \
  -e "/^SetEnv DB_NAME /  s|.*|SetEnv DB_NAME \"${DB_NAME}\"|" \
  -e "/^SetEnv APP_MODE / s|.*|SetEnv APP_MODE \"${APP_MODE}\"|" \
  -e "/^# Auto-generated by / s|.*|# Auto-generated by ${SCRIPT_NAME}|" \
	"$HTACCESS_FILE"

# -------------------------------------------------
# If no SetEnv lines exist, append them
# -------------------------------------------------
if ! grep -q "SetEnv DB_HOST" "$HTACCESS_FILE"; then
  {
    echo ""
    echo "# Auto-generated by ${SCRIPT_NAME}"
    echo "SetEnv DB_HOST \"${DB_HOST}\""
    echo "SetEnv DB_USER \"${DB_USER}\""
    echo "SetEnv DB_PASS \"${DB_PASS}\""
    echo "SetEnv DB_NAME \"${DB_NAME}\""
    echo "SetEnv APP_MODE \"${APP_MODE}\""
  } >> "$HTACCESS_FILE"
fi

# -------------------------------------------------
#  Restart LAMPP so Apache inherits the variables
# -------------------------------------------------
sudo /opt/lampp/lampp restart


# -------------------------------------------------
#  Verify that PHP sees the variables (optional)
# -------------------------------------------------
php -r 'printf(
    "DB_HOST=%s\nDB_USER=%s\nDB_PASS=%s\nDB_NAME=%s\nAPP_MODE=%s\n",
    getenv("DB_HOST"),
    getenv("DB_USER"),
    getenv("DB_PASS"),
    getenv("DB_NAME"),
    getenv("APP_MODE")
);'

