name: CI Build

# Define events that trigger this workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim  # Main container for executing the job

    services:
      postgres:
        image: postgres:alpine  # Service container for the main job
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t  # Password for the PostgreSQL user
          POSTGRES_DB: testdb          # Name of the database to create
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Checkout source code from the repository

      - name: Install dependencies
        run: |  # Run the following commands in the shell
          python -m pip install --upgrade pip wheel  # Upgrade pip and wheel for package management
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"
